spring.application.name=book-my-show
spring.datasource.url=jdbc:postgresql://localhost:5432/bms
spring.datasource.username=postgres
spring.datasource.password=your_database_password
spring.jpa.hibernate.ddl-auto=update
