spring.application.name=book-my-show
spring.datasource.url=jdbc:postgresql://localhost:5432/bms
spring.datasource.username=postgres
spring.datasource.password=Lingesh@9440
spring.jpa.hibernate.ddl-auto=update